// pages/api/rate-auditor.ts — a user-agent rates + comments an AUDITOR after a task.
// The comment is AI-generated (gpt-4.1-nano) unless one is supplied, then recorded on
// HCS (the auditor's review topic + good/bad voting topic) AND logged to the DB
// (auditors.json profile + users.json reviews_given). Streams progress — use `curl -N`.
//
//   curl -N "http://localhost:3000/api/rate-auditor?agent_id=0.0.9227937&skill=safe-weather-skill&verdict=SAFE&rating=5"
//   curl -N "http://localhost:3000/api/rate-auditor?agent_id=0.0.9227937&auditor=0.0.9227928&skill=pdf-toolkit&verdict=DANGEROUS&rating=5&comment=Great%20catch"
//
// Params:
//   agent_id  — the reviewing user-agent (defaults to the demo REQUESTER)
//   auditor   — the auditor being reviewed (defaults to the demo AUDITOR)
//   skill     — the skill that was audited
//   verdict   — SAFE | DANGEROUS (shapes the AI comment; default SAFE)
//   rating    — 1..5 stars (default 5)
//   comment   — optional; if omitted, generated by gpt-4.1-nano
//   task_topic — optional task topic id to link the review to
import type { NextApiRequest, NextApiResponse } from "next";
import { getClient, submitMessage, buildReview, buildHCS20Mint } from "@/lib/hedera";
import { AUDITOR, AUDITOR_REVIEW_TOPIC, AUDITOR_VOTING_TOPIC, REQUESTER } from "@/lib/demo-skills";
import { generateReviewComment } from "@/lib/auditor";
import { saveAuditorReview } from "@/lib/db.mjs";

export const config = { api: { responseLimit: false }, maxDuration: 120 };

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const q = req.method === "POST" ? { ...req.query, ...(req.body ?? {}) } : req.query;
  const reviewer = String(q.agent_id ?? q.agentId ?? q.reviewer ?? REQUESTER).trim();
  const auditor = String(q.auditor ?? AUDITOR).trim();
  const skill = String(q.skill ?? "").trim();
  const verdict: "SAFE" | "DANGEROUS" = String(q.verdict ?? "SAFE").toUpperCase() === "DANGEROUS" ? "DANGEROUS" : "SAFE";
  const rating = Math.max(1, Math.min(5, Math.round(Number(q.rating) || 5)));
  const taskTopicId = q.task_topic ? String(q.task_topic) : undefined;
  let comment = (q.comment ? String(q.comment) : "").trim();

  res.writeHead(200, {
    "Content-Type": "text/plain; charset=utf-8",
    "Cache-Control": "no-store, no-transform",
    "X-Accel-Buffering": "no",
  });
  const w = (s = "") => res.write(s + "\n");

  if (!skill) {
    w("ERROR: pass ?skill=<name> (and optionally agent_id, auditor, verdict, rating, comment)");
    return void res.end();
  }

  let client: ReturnType<typeof getClient> | undefined;
  try {
    w(`\n  MARS · rate auditor`);
    w(`  reviewer ${reviewer} → auditor ${auditor}`);
    w(`  skill ${skill} · verdict ${verdict} · ${rating}/5`);

    // 1) AI comment (gpt-4.1-nano) unless one was supplied
    let source = "provided";
    if (!comment) {
      const r = await generateReviewComment({ skill, verdict, rating, auditor });
      comment = r.comment;
      source = r.source;
    }
    w(`  comment (${source}): "${comment}"`);

    // 2) record on HCS — the auditor's review topic + good/bad voting topic
    client = getClient();
    const reviewSeq = (await submitMessage(client, AUDITOR_REVIEW_TOPIC, buildReview({ target: auditor, reviewer, rating, comment, role: "auditor" }))).sequenceNumber;
    const voteSeq = (await submitMessage(client, AUDITOR_VOTING_TOPIC, buildHCS20Mint("good", String(rating), auditor))).sequenceNumber;
    w(`  ⛓ recorded on HCS — review seq ${reviewSeq} · vote seq ${voteSeq}`);

    // 3) log into the DB (auditor profile + user's reviews_given)
    const saved = saveAuditorReview({ auditorId: auditor, reviewerId: reviewer, rating, comment, skill, verdict, reviewSeq, voteSeq, taskTopicId });
    w(`  saved → auditors.json[${auditor}] avg ${saved.rating} over ${saved.review_count} · users.json[${reviewer}].reviews_given`);

    w(`RESULT ${JSON.stringify({ auditor, reviewer, rating, comment, source, auditor_avg: saved.rating, review_seq: reviewSeq, vote_seq: voteSeq })}`);
  } catch (e: unknown) {
    w(`\nERROR: ${e instanceof Error ? e.message : "rate-auditor failed"}`);
  } finally {
    try {
      client?.close();
    } catch {}
    res.end();
  }
}
